//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2.ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrenor
    {
        public int Id { get; set; }
        public decimal Amaas { get; set; }
        public string Aname { get; set; }
        public string Aulke { get; set; }
        public string Akulup { get; set; }
        public int BaskanId { get; set; }
    }
}
