//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2.ornek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FutbolContainer : DbContext
    {
        public FutbolContainer()
            : base("name=FutbolContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Futbolcu> FutbolcuSet { get; set; }
        public virtual DbSet<Antrenor> AntrenorSet { get; set; }
        public virtual DbSet<SK> SKSet { get; set; }
        public virtual DbSet<Baskan> BaskanSet { get; set; }
    
        public virtual ObjectResult<unvanagorebaskan_Result> unvanagorebaskan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<unvanagorebaskan_Result>("unvanagorebaskan");
        }
    
        public virtual ObjectResult<yasagorebaskan_Result> yasagorebaskan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<yasagorebaskan_Result>("yasagorebaskan");
        }
    }
}
