//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2.ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Futbolcu
    {
        public int FutbolcuId { get; set; }
        public string Fname { get; set; }
        public string Fulke { get; set; }
        public decimal Fmaas { get; set; }
        public string Fkulup { get; set; }
        public int AntrenorId { get; set; }
    }
}
