//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirst2.ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class SK
    {
        public int Id { get; set; }
        public string Kname { get; set; }
        public decimal Kdeger { get; set; }
        public int Kcalısans { get; set; }
    }
}
